'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),cp=require('node:child_process'),vm=require('node:vm');
const {describe,siteSummary}=require('../ppp-ui.js'),{html,engine,compute,inputs}=require('./ppp-fixture.js');
const baseline=cp.execFileSync('git',['show','12213ec05769808f9aa895c47b6258d28bcb2493:mixto.html'],{encoding:'utf8'});
const originalEngine=baseline.slice(baseline.indexOf('  function parkingPerUnit'),baseline.indexOf('  function calculate(){'));
test('Original 81 inputs and all original metric IDs survive the redesign',()=>{const fields=s=>[...s.matchAll(/<input\b[^>]*type="range"[^>]*>/g)].map(([tag])=>tag).sort();assert.equal(fields(html).length,81);assert.deepEqual(fields(html),fields(baseline));const ids=s=>[...s.matchAll(/id="((?:lbl|hud)[^"]+)"/g)].map(m=>m[1]).sort();assert.deepEqual(ids(html),ids(baseline));});
test('The financial engine is byte-identical to the shipped baseline',()=>assert.equal(engine,originalEngine));
test('Synthetic sensitivities: baseline and new presentation read identical outputs',()=>{const ctx=vm.createContext({});vm.runInContext(originalEngine,ctx);for(const patch of [{},{inPreViv:56000},{inCOS:55,inCUS:8,inTerreno:3200},{inMaxDeuda:0,inEquity:0},{inInventarioExplicito:1,inUnidadesA:13,inUnidadesB:20,inUnidadesC:7},{inAporteTierra:0},{inPIK:22,inCostRas:25000}]){const v={...inputs,...patch},r=compute(v);assert.deepEqual(r,JSON.parse(JSON.stringify(ctx.computar(v))));assert.equal(describe(r).length,5);}});
test('Missing source values are not represented as zero or a healthy score',()=>{const cards=describe({p:{}});assert.match(cards[0].main,/—/);assert.ok(cards.every(c=>c.graphic.values.every(v=>v===null||v===undefined)));assert.match(cards[2].main,/—/);});
test('Composition and reconciliation use the same confirmed state',()=>{const r=compute(inputs),cards=describe(r);assert.ok(Math.abs(cards[1].graphic.values.reduce((a,b)=>a+b,0)-1)<1e-9);assert.ok(Math.abs(cards[2].graphic.values.reduce((a,b)=>a+b,0)-1)<1e-9);const delta=r.resSell-(r.mixLoftUnits*r.p.m2Loft+r.mix2Units*r.p.m22Rec+r.mix3Units*r.p.m23Rec);if(Math.abs(delta)>.5)assert.match(cards[0].note,/conciliar/);assert.match(cards[1].sections[0].note,/no son contratos/);assert.match(cards[3].sections[0].note,/no significa crédito autorizado/);});
test('All inline scripts parse',()=>{for(const m of html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g))new vm.Script(m[1]);});

test('Terrain is visible in the closed summary, with capacity and product preserved',()=>{const r=compute(inputs),card=describe(r)[0];assert.match(card.main,/1,800.*terreno/);assert.ok(card.sub.includes(String(r.units)+' depas'));assert.ok(card.sections[0].items.some(x=>x.label==='Terreno'));});
test('Native site preserves measured areas and explicit discrepancies without changing the model',()=>{const r=compute(inputs),before=JSON.stringify(r),site={uso:[[4,0],[1,3]],resumen:[['Total terreno',1900],['Cuerpo sur',500]]},stages=[['Traslado completo confirmado',0],['Continuidad de rentas','PENDIENTE']];const d=siteSummary(r,site,stages);assert.equal(d.difference,100);assert.equal(d.conditions.length,2);assert.equal(JSON.stringify(r),before);assert.equal(siteSummary(r,{uso:[[9]]},stages),null);assert.equal(siteSummary(r,{uso:[]},stages),null);assert.equal(siteSummary(r,{uso:[[0]],resumen:[['Total terreno','']]},stages).difference,null);});

const {architectureScale}=require('../ppp-ui.js');
test('Architectural dimensions preserve square-root area and linear height on fixed references',()=>{const a=architectureScale({terrain:1600,plate:800,height:30}),b=architectureScale({terrain:6400,plate:3200,height:60});assert.equal(b.ground,a.ground*2);assert.equal(b.plate,a.plate*2);assert.equal(b.height,a.height*2);assert.deepEqual(architectureScale({}),{ground:null,plate:null,height:null});assert.deepEqual(architectureScale({terrain:0,plate:0,height:0}),{ground:0,plate:0,height:0});assert.deepEqual(architectureScale({terrain:12000,plate:13000,height:150}),{ground:90,plate:90,height:125});});
