const test=require('node:test'),assert=require('node:assert/strict');
const {create,latestRegistered}=require('../ppp-version-bridge.js');
const list=[{id:'older',nombre:'Anterior',inputs:{inArea:10}},{id:'newer',nombre:'Última inscrita',inputs:{inArea:20}}];
function setup(initial={}){let listener;const sent=[],parent={postMessage:m=>sent.push(m)},win={parent,location:{href:'https://example.test/potenciales-yod/macrolotes.html?agent=1',origin:'https://example.test'},document:{referrer:'https://example.test/yod-portal/despacho3d/index.html'},addEventListener:(n,f)=>listener=f,removeEventListener(){}};
 const view={caseId:'board-a',scenarios:structuredClone(list),active:'older'},bridge=create({modelType:'macrolotes',read:()=>view,win});
 bridge.remember({caseId:'board-a',revision:'rev1',scenarios:list,active:'older'});
 const send=m=>listener({source:parent,origin:win.location.origin,data:{version:1,case_id:'case-a',board_case_id:'board-a',nonce:'session-a',...m}});
 send({type:'yod:ppp:hello',...initial});return {bridge,view,send,sent,win};}
test('latest registered is array order, not active or a date invented from the name',()=>{assert.equal(latestRegistered(list),'newer');assert.throws(()=>latestRegistered([...list,list[0]]));});
test('viewing another version preserves defended version and all originals',()=>{const {bridge,view}=setup();let s=bridge.snapshot();assert.equal(s.scenario_id,'newer');assert.equal(s.version_context.viewed_scenario_id,'older');assert.equal(s.inputs.inArea,20);assert.equal(s.pending,false);view.active='newer';assert.equal(bridge.snapshot().scenario_id,'newer');assert.equal(bridge.snapshot().version_context.viewed_scenario_id,'newer');assert.deepEqual(view.scenarios,list);});
test('unsaved edits are pending and never become canonical values or local calculated results',()=>{const {bridge,view}=setup();view.scenarios[1].inputs.inArea=900;let s=bridge.snapshot();assert.equal(s.pending,true);assert.equal(s.inputs.inArea,20);assert.deepEqual(s.results,{});assert.ok(s.fields.every(f=>!f.editable));});
test('read-only model refuses every apply without a business write',()=>{const {send,sent}=setup();send({type:'yod:ppp:apply',proposal:{request_id:'request-1'}});assert.equal(sent.at(-1).receipt.error,'read_only_model');});
test('late case data, wrong mapping, foreign parent and changed handshake cannot switch authority',()=>{const x=setup();const count=x.sent.length;x.send({type:'yod:ppp:hello',case_id:'case-b',nonce:'session-b'});assert.equal(x.sent.length,count);x.view.caseId='board-b';assert.equal(x.bridge.snapshot(),null);x.bridge.dispose();x.send({type:'yod:ppp:read'});assert.equal(x.sent.length,count);});
test('refresh/new registration cannot silently change pinned defended version',()=>{const x=setup();const next=[...list,{id:'last',nombre:'Nueva',inputs:{inArea:40}}];x.view.scenarios=next;x.bridge.remember({caseId:'board-a',revision:'rev2',scenarios:next,active:'older'});assert.equal(x.bridge.snapshot().scenario_id,'newer');x.bridge.invalidate();assert.equal(x.bridge.snapshot().confirmed,false);});

test('same handshake cannot repin the defended version',()=>{const x=setup();const count=x.sent.length;x.send({type:'yod:ppp:hello',scenario_id:'older'});assert.equal(x.sent.length,count);assert.equal(x.bridge.snapshot().scenario_id,'newer');x.send({type:'yod:ppp:hello',scenario_id:'newer'});assert.ok(x.sent.length>count);assert.equal(x.bridge.snapshot().scenario_id,'newer');});
test('explicit initial pin survives retries and attempts to replace it',()=>{const x=setup({scenario_id:'older'});assert.equal(x.bridge.snapshot().scenario_id,'older');x.send({type:'yod:ppp:hello',scenario_id:'newer'});assert.equal(x.bridge.snapshot().scenario_id,'older');x.send({type:'yod:ppp:hello',scenario_id:'older'});assert.equal(x.bridge.snapshot().scenario_id,'older');});
